### ISSUE TITLE
建议加入黑暗模式

### ISSUE THREAD

**Issue by zero-hugo** [unicar9/jizhi#104]
建议加入黑暗模式。图可以是夜空，一弯细细的弦月，几缕淡淡的云，配上古诗不是很应景吗。
主要是系统改成黑暗模式之后，其他都黑的，显得这个新标签页面很亮。

**Comment by unicar9** [comment]
> 建议加入黑暗模式。图可以是夜空，一弯细细的弦月，几缕淡淡的云，配上古诗不是很应景吗。
> 主要是系统改成黑暗模式之后，其他都黑的，显得这个新标签页面很亮。

如果只是color scheme会比较简单，如果是暗色背景可能还需要一些时间。。

**Comment by unicar9** [comment]
@zero-hugo 已更新：）
