### ISSUE TITLE
可否把诗词主题放在新建 tab 靠右一点的譬如黄金分割的位置呢？

### ISSUE THREAD

**Issue by Janus-Y** [unicar9/jizhi#127]
因为 tab 基本上都是在右边打开嘛，而且就整个画面的美感来说，不要直接摆在当中更符合诗词或者古汉语的美感？
或者，是不是可以至少提供一个选项。。😂
最新版的竖排就是很贴心的功能呀。点赞 👍

**Comment by unicar9** [comment]
> 因为 tab 基本上都是在右边打开嘛，而且就整个画面的美感来说，不要直接摆在当中更符合诗词或者古汉语的美感？
> 或者，是不是可以至少提供一个选项。。😂
> 最新版的竖排就是很贴心的功能呀。点赞 👍
 
感觉竖版更适合放在偏左或者偏右的地方，会提供一下这个选项吧
