### ISSUE TITLE
建议添加一个 ”猛男硬汉“ 模式, 去除粉色、红色的背景

### ISSUE THREAD

**Issue by junbaor** [unicar9/jizhi#157]
如题，建议添加一个"猛男硬汉"模式, 去除粉色、红色的背景。

身后站着同事，打开 tab 发现是粉色，气氛有点尴尬。

**Comment by unicar9** [comment]
> 如题，建议添加一个"猛男硬汉"模式, 去除粉色、红色的背景。
> 
> 身后站着同事，打开 tab 发现是粉色，气氛有点尴尬。

左右方向键是可以更换颜色的。。如果手速够快换掉粉色背景也可以显得很猛男哦。。
