### ISSUE TITLE
书签栏

### ISSUE THREAD

**Issue by uniquepengpeng** [unicar9/jizhi#179]
你好:
      默认书签栏全局隐藏,系统自带的新标签页也会显示书签栏(书签较少,不想一直展示).
     几枝新标签页不会展示.能不能给个设置实现类似的效果呢?

**Comment by henryxrl** [comment]
+10086
无法放弃几枝的精美，但是又希望添加一些实用性的功能~ 比如，鼠标划过页面顶端的时候现实书签栏的内容
