### ISSUE TITLE
传统色字体显示不完整及保存背景相关问题

### ISSUE THREAD

**Issue by HSantu** [unicar9/jizhi#188]
有些颜色的第一个字会被”砍头“，例如图
![image](https://user-images.githubusercontent.com/23703054/88279960-848d0e00-cd17-11ea-9465-019a7e087ccf.png)
![image](https://user-images.githubusercontent.com/23703054/88279972-88209500-cd17-11ea-8d7f-0c8ce1cf1cf8.png)
![image](https://user-images.githubusercontent.com/23703054/88279977-8b1b8580-cd17-11ea-9b2b-58c790eb83fb.png)
![image](https://user-images.githubusercontent.com/23703054/88279985-8eaf0c80-cd17-11ea-97f6-0a41f2d61a94.png)
以及保存背景时是否有可能把设置按钮隐藏呢？

**Comment by sfyumi** [comment]
保存图片隐藏设置按钮的一个思路：
toPNG 之前把设置按钮隐藏，
toPNG 之后再把设置按钮还原。
```
var menu = document.getElementById('menu');
menu.hidden=true;
```
