### ISSUE TITLE
能增加深色主题

### ISSUE THREAD

**Issue by bitdan** [unicar9/jizhi#209]
在全局使用深色主题情况下,新打开的网页实在是太亮眼了,希望添加一个深色主题,

**Comment by henryxrl** [comment]
等不及了，自己动手改了一下
![Snipaste_2020-12-11_20-45-56](https://user-images.githubusercontent.com/7662954/101975510-fcd66c00-3bf1-11eb-8263-2e032807233a.png)

**Comment by unicar9** [comment]
@bitdan 已更新~：）
