### ISSUE TITLE
新标签页的名称无法跟随浏览器设置的语言

### ISSUE THREAD

**Issue by BrandNewLifeJackie26** [unicar9/jizhi#221]
firefox中语言是中文，但是加载了插件之后，新标签页名字变成了new tab，没有跟随浏览器设置。

不知道about:newtab这个跟随浏览器设定是怎么实现的。我想是不是tabs.create()函数里面可以设定，查了文档暂时没看到什么好办法。

可能对功能影响不大，原谅我的强迫症 谢谢 XD

**Comment by XueMeijing** [comment]
> firefox中语言是中文，但是加载了插件之后，新标签页名字变成了new tab，没有跟随浏览器设置。
> 
> 不知道about:newtab这个跟随浏览器设定是怎么实现的。我想是不是tabs.create()函数里面可以设定，查了文档暂时没看到什么好办法。
> 
> 可能对功能影响不大，原谅我的强迫症 谢谢 XD

Chrome里可以js设置，但是会从默认chrome://newtab跳一下  document.title=chrome.i18n.getMessage("newTabName")

**Comment by unicar9** [comment]
目前 new tab 是硬写的，我查看一下i18n相关文档，看看能不能随着浏览器设置自动切换
