### ISSUE TITLE
[Bug]新版本下保存图片文字的透明度好像有点问题

### ISSUE THREAD

**Issue by douMax** [unicar9/jizhi#25]
![jizhi](https://user-images.githubusercontent.com/28494194/61373445-301daa00-a8dd-11e9-9480-0e41de64bcb2.png)
如图。
不太清楚原因，可能和 html2canvas 有关系？

**Comment by unicar9** [comment]
@douMax 会尽快处理 ：）

**Comment by arthur-zheng** [comment]
我的发现：
1. blob情况下，文字透明度正常（猜测因为color-name不存在）
2. waves情况下，verses的透明度和color-name一致（0.1）
怀疑是html2canvas的bug把color-name的透明度误投射到verses文字上。

解决办法：
初始化color-name的透明度为1. 透明效果用color：rgba设定。这样color-name就不会有opacity=0.1的时候。

**Comment by unicar9** [comment]
> 我的发现：
> 
> 1. blob情况下，文字透明度正常（猜测因为`color-name`不存在）
> 2. waves情况下，verses的透明度和`color-name`一致`（0.1）`
>    怀疑是`html2canvas`的bug把`color-name`的透明度误投射到verses文字上。
> 
> 解决办法：
> 初始化`color-name: opacity=1`。透明的效果用`color：rgba()`实现。这样`color-name`就不会有opacity=0.1的时候。

哈哈昨晚上查到这个问题然后就去睡啦，多谢，我来改哈
