### ISSUE TITLE
几枝修改版能否上架为 Edge 外接程序?

### ISSUE THREAD

**Issue by wutong233** [unicar9/jizhi#266]
[修改版](https://github.com/wutong233/jizhi-m)的插件名并不相同.
会在各处标明原作者并保留贡献者.

其他问题: 图标是否开放使用? 本仓库采用何种开源协议?

求大佬告知, 若不予许可, 那我就只自用解压缩扩展了.

**Comment by unicar9** [comment]
哈喽，

谢谢关注，我还是想保留插件在其他浏览器的发布权利，接下来会陆续上架Edge和Safari。

我也会添加更具体的开源协议，我的意愿是移植到其他平台没有问题，之前也有同学移植到安卓系统了，图标可以复用也可以用其他的，但是名字最好还是保留几枝，注明一下来源就行。
