### ISSUE TITLE
江西拙楷在显示四字颜色名称时容易超高

### ISSUE THREAD

**Issue by cagecity** [unicar9/jizhi#276]
因为字体比较大，而且字间距较大，在笔记本的分辨率下比较容易超高，第四个字不能显示完整。可以将拙锴显示颜色名称时的字体和间距调小一些？

这次调整了默认字体，建议在左下角设置按钮处增加一个 “可以自定义字体” 的提示，避免用户不适应新字体。

**Comment by unicar9** [comment]
@cagecity 谢谢你的意见，我会调整一下。。。顺便考虑加入推送功能。。。这次提供字体选项的初衷还是挺重要的。。只不过在 readme 说了没太多人看到。。。
