### ISSUE TITLE
字体切换没有效果

### ISSUE THREAD

**Issue by tp1415926535** [unicar9/jizhi#279]
三种字体不管选哪个，最后字体效果都只有江西拙楷。
chrome商店的版本，卸载重装了也是一样。

**Comment by unicar9** [comment]
> 三种字体不管选哪个，最后字体效果都只有江西拙楷。
> chrome商店的版本，卸载重装了也是一样。

哈喽，除了江西拙楷，其他字体都需要远程获取，点击字体之后请稍作等待。。。我会加一个加载图标来增强视觉上的指示。。。
