### ISSUE TITLE
[问题反馈] 浏览器最大化时，底部会有一条很显眼的白线

### ISSUE THREAD

**Issue by XIU2** [unicar9/jizhi#288]
这个问题好像很早就有了，今天显得没事就来反馈一下，强迫症看着难受。

> Chrome 浏览器、几枝 v2.5.0

## \# 问题描述

浏览器最大化，Win10 **深色模式**，任务栏是**黑色**的，这条白线就**很显眼**了。
![04](https://user-images.githubusercontent.com/54703944/112754915-ef15ec80-9010-11eb-88a7-419742c9349d.png)  
![02](https://user-images.githubusercontent.com/54703944/112754913-ede4bf80-9010-11eb-84db-2fb26efd5caa.png)
![06](https://user-images.githubusercontent.com/54703944/112755636-19b57480-9014-11eb-8ce1-a8795b4b30a1.png)

浏览器最大化，Win10 **浅色模式**，任务栏是**白色**的，就**看不见**这个白线了。
![05](https://user-images.githubusercontent.com/54703944/112755499-854b1200-9013-11eb-8783-00f66fdb6a57.png)

> 另外，不管是否开启扩展设置中的 <kbd>黑夜模式</kbd>，无论背景是 <kbd>Waves</kbd> 还是 <kbd>Blobs</kbd>，都会有这条白线。

****

## \# 问题分析

初步判断是因为**网页背景颜色是白色**导致的，你看这个 GIF 动图：

当我浏览器窗口化并**调整大小**时，可以看到网页背景颜色是白色的（动画绘制会有一点点延迟才会跟上）。

> 窗口化调整大小时，如果是缩小那么不会复现，如果是放大那可能是底部白线。浏览器最大化时，底部始终显示白线。

![01](https://user-images.githubusercontent.com/54703944/112754911-ecb39280-9010-11eb-8e08-b5d5335bfe82.gif)

****

## \# 解决方法

当我通过 F12 开发者工具，调整网页样式后发现：

只要在 `div.app、div#root、body、html` 其中任意一个添加  `background-color: #XXXXXX` 样式都可以**解决白线问题**。

![03](https://user-images.githubusercontent.com/54703944/112754914-ee7d5600-9010-11eb-9f47-db8b9662788d.png)

建议在随机颜色后，顺便修改以上元素之一的样式（`style="background-color: #XXXXXX;"`），该背景颜色值就是随机到的颜色值（当然是底部颜色最深的那个）。

**Comment by unicar9** [comment]
@XIU2 好的辛苦了~~我会尽快修正一下
