### ISSUE TITLE
作者可否考虑在Microsoft edge add-ons商店上架此插件？

### ISSUE THREAD

**Issue by sanziliu** [unicar9/jizhi#385]
虽然chrome商店下载的是通用的，但是edge商店里有两个同名插件：一个似乎是爱好者代为上传，另一个似乎是冒名商业行为（而且有bug）。李鬼李逵分不清楚了。

**Comment by unicar9** [comment]
@sanziliu 谢谢提醒，已经上传了正在审核中。。。

**Comment by sanziliu** [comment]
多谢！

Feng
________________________________
