### ISSUE TITLE
README.md 里的 Firefox 链接错误

### ISSUE THREAD

**Issue by sheepzh** [unicar9/jizhi#388]
https://addons.mozilla.org/zh-CN/firefox/addon/jizhi/

显示找不到扩展

**Comment by lqhl** [comment]
还是有问题，有 firefox 插件的离线安装包吗？

**Comment by iPixelOldC** [comment]
大佬，这个链接好像又无了，求补，谢谢。以及能否提供离线版的安装包呢？或者直接依托github release来更新插件。在addons商店出问题时做备选项。

> @sheepzh 谢谢提醒。。。审核有点问题我去重新一下。。。
