### ISSUE TITLE
诗题过长时浏览器显示不全

### ISSUE THREAD

**Issue by xmvske** [unicar9/jizhi#389]
## 问题描述
偶然一次遇到一首题目叫【韩冬郎即席为诗相送一座尽惊他日余方追吟连宵侍坐裴回久之句有老成之风因成二绝寄酬兼呈畏之员外·-其一】的诗，诗名一共47个字，导致在浏览器中显示上半部分被遮挡。 效果如下

![image](https://user-images.githubusercontent.com/65944680/154664898-5b7970f9-01fa-45da-875d-591f9b75b5f4.png)

## 问题建议
 是否可以通过<b>适应字体大小</b>、<b>多行显示</b>或者<b>超长省略</b>等方式来处理。

**Comment by niu541412** [comment]
同样问题，可以考虑题目换行。
<img width="1384" alt="QQ20220402-103739@2x" src="https://user-images.githubusercontent.com/3370897/161362587-f262adf6-2774-4834-ac9c-e51d2d4a255a.png">

**Comment by unicar9** [comment]
@xmvske @niu541412 多谢发现，此 bug 会在更新版修正
