### ISSUE TITLE
CPU 和 GPU 占用率高

### ISSUE THREAD

**Issue by xnng** [unicar9/jizhi#4]
操作系统：win10

此插件在打开时会导致 cpu 和 gpu 占用率飙升，风扇的声音都能听得到。

![微信截图_20190324163727](https://user-images.githubusercontent.com/38936252/54876989-a93b5200-4e53-11e9-8fa2-c29ee11a400f.png)
![微信截图_20190324163833](https://user-images.githubusercontent.com/38936252/54876990-a9d3e880-4e53-11e9-9319-ef5f13554f88.png)

**Comment by unicar9** [comment]
@xnng 更新了一下动效的机制，默认静态波浪不执行 draw()，这是个每秒执行60次的循环，之前只是把时间增值一直设为0，所以不管动不动都一直维持60fps。关于优化 canvas 动画性能我再研究下好了。你可以更新看看。

**Comment by xnng** [comment]
感谢作者，我的问题基本上解决了，静态波浪已经不会再引起额外的 gpu 占用升高了，完全可以接受。
