### ISSUE TITLE
在谷歌火狐edge都搜不到这个插件了

### ISSUE THREAD

**Issue by outlawBin** [unicar9/jizhi#401]
用这个插件好几年了，前几天换系统后安装浏览器同步，没看到几枝，去扩展商店也找不到了，请问是被下架了吗？

**Comment by unicar9** [comment]
@outlawBin https://chrome.google.com/webstore/detail/%E5%87%A0%E6%9E%9D/hfohpokminpknagcgncibpacohagppjn 火狐是有点问题，谷歌chrome 还在啊。。。上面链接可以打开么？

**Comment by outlawBin** [comment]
火狐找不到，谷歌商店能找到但是安装报错，包损坏，我去第三方网站 https://chrome.zzzmh.cn/ 下载安装也是报错，包损坏。我从仓库下载打包安装，这样才能在谷歌安装上。

**Comment by outlawBin** [comment]
刚才又试了一次，在谷歌商店安装成功，不过在火狐还是没找到，期待大佬解决火狐的问题
