### ISSUE TITLE
[需求]有没有设置自定义数据源(切换今日诗词API为其他自由设置的API)的计划

### ISSUE THREAD

**Issue by KangSpace** [unicar9/jizhi#416]
请问有没有设置自定义数据源(切换今日诗词API为其他自由设置的API)的计划？
需求:
1. 可以在设置中配置自定义的数据源API接口，接口字段可自定义或按规则自动识别。

**Comment by unicar9** [comment]
@KangSpace 诗词功能是几枝的特色，这个自由度暂时不考虑了，如果有需要可以自己改哈。。
