### ISSUE TITLE
[需求]随系统自动切换黑夜模式

### ISSUE THREAD

**Issue by ylcz2014** [unicar9/jizhi#418]
希望加入随系统自动切换黑夜模式，类似dark reader

**Comment by unicar9** [comment]
@ylcz2014 多谢建议。。。有挺多朋友都提过，最近有点忙，我尽快加上这个功能吧。。。

**Comment by fyqqyf** [comment]
需求+1，谢谢大佬！

**Comment by unicar9** [comment]
@ylcz2014 @fyqqyf 多谢建议，已做好，会在下一版更新：）
