### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by xu-jiayin** [unicar9/jizhi#424]
如图[https://static01.imgkr.com/temp/7ab494620ffc4545a07cdc2c1bc2165d.png](https://static01.imgkr.com/temp/7ab494620ffc4545a07cdc2c1bc2165d.png)

**Comment by xu-jiayin** [comment]
[https://static01.imgkr.com/temp/7ab494620ffc4545a07cdc2c1bc2165d.png](url)

**Comment by unicar9** [comment]
@xu-jiayin 感谢发现，已经调试好，会在下一版更新修正哈。。。：）
