### ISSUE TITLE
字体ttf 偏大

### ISSUE THREAD

**Issue by Pearyman** [unicar9/jizhi#5]
- node服务 动态解析获取接口的文字

- 压缩 或换个别的小的chrome支持的字体格式

- 用一个cdn， 善用一下缓存。preload

**Comment by xnng** [comment]
压缩比较难，目前的压缩工具都只能压缩已知文字内容，例如 font-spider 压缩后就会丢失服务端请求的文字

node 服务动态解析文字好像成本有点高

cdn 我试了下，不能解决根本问题，文件偏大，在缓存生成之前，首次请求字体文件还是比较耗时。

**Comment by Pearyman** [comment]
@xnng  微笑.jpg
