### ISSUE TITLE
[Feature Request] 点击 play 后播放白躁声

### ISSUE THREAD

**Issue by baurine** [unicar9/jizhi#9]
只有波浪动画有点单调，可否同时播放白躁声。(我原以为是有的，结果听了半天也没听到一丝声音，仔细阅读了 RAEDME 后发现实际并无此功能)

**Comment by unicar9** [comment]
@baurine 确实没想到这个功能，因为这只是 new tab page，估计用户并不会停留很久，加入白噪音的话是准备什么场景利用呢？

**Comment by baurine** [comment]
只是觉得配点背景音乐的话会更有意境一些，也会让我多停留一会在那，或许会一直开一个 tab 在那欣赏。不过如果觉得意义不大的话就 pass 掉吧。

**Comment by crimx** [comment]
哈哈，可以调素琴阅金经的 new tab page

**Comment by baurine** [comment]
正好今天又在 v2ex 上看到一个贴子: [五分钟撸了一个写代码听雨声的小站](https://www.v2ex.com/t/549569) 可以参考一下。

**Comment by daihy8759** [comment]
> 正好今天又在 v2ex 上看到一个贴子: [五分钟撸了一个写代码听雨声的小站](https://www.v2ex.com/t/549569) 可以参考一下。

我参照jizhi实现了一个 [链接](https://github.com/daihy8759/nanguo)

**Comment by baurine** [comment]
> > 正好今天又在 v2ex 上看到一个贴子: [五分钟撸了一个写代码听雨声的小站](https://www.v2ex.com/t/549569) 可以参考一下。
> 
> 我参照jizhi实现了一个 [链接](https://github.com/daihy8759/nanguo)

赞！但字体还是方正金陵的好看啊。

**Comment by unicar9** [comment]
> > 正好今天又在 v2ex 上看到一个贴子: [五分钟撸了一个写代码听雨声的小站](https://www.v2ex.com/t/549569) 可以参考一下。
> 
> 我参照jizhi实现了一个 [链接](https://github.com/daihy8759/nanguo)

太棒了！我也准备改写成 react 的来着，如果遇到问题希望能不吝赐教。：）

**Comment by daihy8759** [comment]
> > > 正好今天又在 v2ex 上看到一个贴子: [五分钟撸了一个写代码听雨声的小站](https://www.v2ex.com/t/549569) 可以参考一下。
> > 
> > 
> > 我参照jizhi实现了一个 [链接](https://github.com/daihy8759/nanguo)
> 
> 太棒了！我也准备改写成 react 的来着，如果遇到问题希望能不吝赐教。：）

😃我是菜鸟，不过p5写法不是很React，有时间我想把他给换了
